dist: bionic
language: php

env:
  global:
    - SETUP=stable

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: COMPOSER=composer.dingo.json
      name: "With Dingo router"
    - php: 7.4
      env: SETUP=lint
      name: "Lint code"
    - php: 7.2
    - php: 7.2
      env: SETUP=lowest
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest
    - php: 7.4
      # No lowest for 7.4 because the lowest (Laravel 5.8) doesn't support 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi
  - if [[ $SETUP = 'lint' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; composer lint -- --memory-limit 1G; fi

script:
  - if [[ $SETUP = 'lint' ]]; then exit 0; fi; composer test-parallel-ci;
