language: php

php:
  - 7.0.0
  - 7.1.3
  - 7.2

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --prefer-stable $PREFER_LOWEST

script:
  - composer test-ci

before_install:
  - pip install --user codecov

after_success:
  - codecov
