language: php

php:
  - 7.0.0
  - 7.1.3
  - 7.2.0

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

stages:
  - name: test
  - name: lint
jobs:
  include:
    - stage: test
      script: composer test-ci
      before_script:
        - travis_retry composer self-update
        - travis_retry composer update --no-interaction --prefer-dist $PREFER_LOWEST

    - stage: lint
      script: composer lint

before_install:
  - pip install --user codecov

after_success:
  - codecov
