language: php

php:
  - 7.3
  - 7.2

env:
  - PREFER_LOWEST=""
  - PREFER_LOWEST="--prefer-lowest"

jobs:
  include:
    - script: composer lint
      name: "Lint code"
      php: 7.3
      env: PREFER_LOWEST=""

script: composer test-ci
before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist $PREFER_LOWEST
