language: php

php:
  - 7.2.0
  - 7.1.3
  - 7.0.0

env:
  - PREFER_LOWEST="--prefer-lowest"

jobs:
  include:
    - before_script: composer update --no-interaction --prefer-dist $PREFER_LOWEST
      script: composer lint
      name: "Lint code"
      env:
      - PREFER_LOWEST=""
      php: 7.2.0

script: composer test-ci
before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist $PREFER_LOWEST

before_install:
  - pip install --user codecov

after_success:
  - codecov
