language: php

php:
  - 7.1.3
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - composer test-ci

before_install:
  - pip install --user codecov

after_success:
  - codecov
